-- Supabase Auth users cannot be created by a database migration.
-- Run api/create_demo_user.py with SUPABASE_SERVICE_ROLE_KEY after applying migrations.
-- The script creates or finds the Auth user and replaces demo-organizer IDs in seed rows.