-- Disable RLS for testing
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_tiers DISABLE ROW LEVEL SECURITY;
ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendees DISABLE ROW LEVEL SECURITY;